# Generated by Django 3.2.6 on 2021-09-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210906_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='height',
            field=models.CharField(help_text='Provide height in decimal (e.g 1.63)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examinerprofile',
            name='height',
            field=models.CharField(help_text='Provide height in decimal (e.g 1.63)', max_length=200, null=True),
        ),
    ]
